#!/usr/bin/env sh

[ -z "$1" ] || [ -z "$2" ] && echo "usage: shgen [INPUT FILE] [OUTPUT FILE]" \
    && exit 1

tmpfile=$(mktemp --suffix=shgen)

cat << EOF > "$tmpfile"
#!/usr/bin/env sh
cat << CONF > "$2"
$(cat "$1")
CONF
EOF

chmod +x "$tmpfile"
. "$tmpfile"
rm -f "$tmpfile"
