#!/usr/bin/env sh

# check for lack of arguments before anything else
[ -z "$1" ] || [ -z "$2" ] && echo "usage: xgen [INPUT FILE] [OUTPUT FILE]" && exit 1

input=$1
output=$2
tmpfile=/tmp/xgenapply
cp $input $tmpfile

# function to return xresources colours (e.g. #808080) and dpi, etc.
xquery () {
    xrdb -query | grep $1 | awk '{print $NF; exit}'
}

# return hex without hash - useful in some instances
xquerystrip () {
    col=$(xquery $1)
    echo ${col#\#}
}

# get exact DPI as scale factor (DPI 96 = scale 1)
xreplace () {
    [ "$(grep "$1" "$input")" ] && sed -i "s/$1/$2/g" $tmpfile
}

apply() {
    xreplace "\$(xquery background)" "$(xquery background)"
    xreplace "\$(xquery foreground)" "$(xquery foreground)"
    for num in `seq 1 15`; do
        xreplace "\$(xquery color${num})" "$(xquery color${num})"
    done
    xreplace "\$(xquery fontmono)" "$(xquery fontmono)"
}

applystrip() {
    xreplace "\$(xquerystrip background)" "$(xquerystrip background)"
    xreplace "\$(xquerystrip foreground)" "$(xquerystrip foreground)"
    for num in `seq 1 15`; do
         xreplace "\$(xquerystrip color${num})" "$(xquerystrip color${num})"
    done
}

# check for "xquery" in file before running check on all below
[ "$(grep "xquery" "$1")" ] && apply

# check for "xquerystrip" in file before running check on all below
[ "$(grep "xquerystrip" "$1")" ] && applystrip

cp $tmpfile $output && rm $tmpfile

