#!/usr/bin/env sh

# check for lack of arguments before anything else
[ -z "$1" ] || [ -z "$2" ] && echo "usage: xgen [INPUT FILE] [OUTPUT FILE]" && exit 1

input=$1
output=$2

# create script in /tmp/ to generate output
tmpfile=/tmp/xgen$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 6)
cp $input $tmpfile

# write temporary script: shebang + custom functions + input file
cat << EOF > $tmpfile
#!/usr/bin/env sh

# function to return xresources colours (e.g. #808080) and dpi, etc.
xquery () {
    xrdb -query | grep \$1 | awk '{print \$NF; exit}'
}

# return hex without hash - useful in some instances
xquerystrip () {
    col=\$(xquery \$1)
    echo \${col#\#}
}

cat << CONF > $output
$(cat $input)
CONF
EOF

# execute script
chmod +x $tmpfile
$tmpfile
rm -f $tmpfile
