#!/bin/sh

# function to return xresources colours
xquery () {
    xrdb -query | grep $1 | awk '{print $NF; exit}'
}

# get exact DPI as scale factor (DPI 96 = scale 1)
XDPI=$(bc <<< "scale=2; $(xquery dpi)/96")

# function to apply DPI to input num
dpi () {
    VAL=$(bc <<< "scale=2; $1 * $XDPI"); # multiply input by DPI
    # return value rounded to nearest integer
    printf "%.0f\n" "$(bc <<< "scale=2; $VAL + 0.01")"
            # add 0.01 so that 2.5 rounds to 3, not 2
}
